PfcWeb.MVC/Controllers/MenuController.cs
using PfcWeb.Domain.Entities;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using System.Web.Security;

namespace PfcWeb.MVC.Controllers
{
    public class MenuController : Controller
    {
        [Authorize(Roles = "CAIXA")]
        public ActionResult MenuFuncCaixa()
        {
            return View();
        }

        [Authorize(Roles = "ESTOQUE")]
        public ActionResult MenuFuncEstoque()
        {
            return View();
        }

        [Authorize(Roles = "GERENTE")]
        public ActionResult MenuGerente()
        {
            return View();
        }
    }
}

PfcWeb.MVC/Controllers/VendaController.cs
using PFC.Data.DAO;
using PfcWeb.Data.DAO;
using PfcWeb.Domain.Entities;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using System.Web.Security;
using System.Web.Services;
using System.Web.UI;

namespace PfcWeb.MVC.Controllers
{
    [Authorize(Roles = "CAIXA")]
    public class VendaController : Controller
    {
        public ActionResult Venda()
        {
            HttpCookie cookie = Request.Cookies.Get("UsuarioID");
            VendaDAO vendaDAO = new VendaDAO();
            Venda venda = new Venda();
            venda.DataHora = DateTime.Now;
            venda.Status = "NÃO FINALIZADO";
            venda.Usuario = new Usuario();
            venda.Usuario.ID = Convert.ToInt32(cookie.Value);

            vendaDAO.CadastrarVenda(venda);

            return View();
        }

        [HttpPost]
        public JsonResult AdicionarProduto(Lote obj)
        {
            HttpCookie cookie = Request.Cookies.Get("UsuarioID");

            VendaDAO vendaDAO = new VendaDAO();
            ItemVenda itemVenda = new ItemVenda();

            itemVenda.Venda = new Venda();

            itemVenda.Venda.ID = vendaDAO.GetLastIdVenda(Convert.ToInt32(cookie.Value));

            ProdutoDAO produtoDAO = new ProdutoDAO();

            LoteController loteController = new LoteController();
            Lote loteSelecionado = loteController.GetLoteByBarcode(obj.Barcode);

            if (loteSelecionado != null)
            {
                loteSelecionado.Produto = produtoDAO.ListarSelecionadoID(loteSelecionado.Produto.ID);

                if (loteSelecionado.ID != 0)
                {
                    itemVenda.Quantidade = Convert.ToInt32(obj.QuantidadeItens);
                    itemVenda.Lote = new Lote();
                    itemVenda.Lote = loteSelecionado;

                    PrateleiraDAO prateleiraDAO = new PrateleiraDAO();

                    Prateleira prateleira = prateleiraDAO.ListarSelecionadoIDLote(loteSelecionado.ID);

                    if (prateleira != null)
                    {
                        if (obj.QuantidadeItens <= prateleira.Quantidade)
                        {
                            ItemVendaDAO itemVendaDAO = new ItemVendaDAO();

                            var QuantidadeAtual = prateleira.Quantidade - obj.QuantidadeItens;
                            prateleiraDAO.AtualizarQuantidade(prateleira.ID, QuantidadeAtual);
                            itemVendaDAO.Cadastrar(itemVenda);

                            if (loteSelecionado.DataValidade < DateTime.Now)
                            {
                                return Json(new
                                {
                                    produtoID = 0,
                                    produtoNome = "ERRO VALIDADE",
                                    produtoValor = 0
                                });
                            }
                            else if (loteSelecionado.DataValidade.AddDays(-31) < DateTime.Now)
                            {
                                loteSelecionado.Produto.ValorUnitario = loteSelecionado.Produto.ValorUnitario - (loteSelecionado.Produto.ValorUnitario * 0.2);

                                return Json(new
                                {
                                    produtoID = loteSelecionado.Produto.ID,
                                    produtoNome = loteSelecionado.Produto.Nome,
                                    produtoValor = loteSelecionado.Produto.ValorUnitario
                                });
                            }
                            else
                            {
                                return Json(new
                                {
                                    produtoID = loteSelecionado.Produto.ID,
                                    produtoNome = loteSelecionado.Produto.Nome,
                                    produtoValor = loteSelecionado.Produto.ValorUnitario
                                });
                            }
                        }
                        else
                        {
                            var quantidade = Convert.ToInt32(obj.QuantidadeItens) - prateleira.Quantidade;
                            return Json(new
                            {
                                produtoID = 0,
                                produtoNome = "ERRO QUANTIDADE",
                                produtoValor = 0,
                                produtoQuantidade = quantidade
                            });
                        }
                    }
                    else
                    {
                        return Json(new
                        {
                            produtoID = 0,
                            produtoNome = "ERRO PRATELEIRA",
                            produtoValor = 0,
                            produtoQuantidade = 0
                        });
                    }

                }
                else
                {
                    return Json(new
                    {
                        produtoID = 0,
                        produtoNome = 0,
                        produtoValor = 0
                    });
                }
            }
            else
            {
                return Json(new
                {
                    produtoID = 0,
                    produtoNome = 0,
                    produtoValor = 0
                });
            }

        }

        [HttpPost]
        public JsonResult FinalizarCompra(string TotalItens, string ValorTotal, string ValorRecebido, string Troco)
        {
            HttpCookie cookie = Request.Cookies.Get("UsuarioID");

            VendaDAO vendaDAO = new VendaDAO();

            int lastID = vendaDAO.GetLastIdVenda(Convert.ToInt32(cookie.Value));

            Venda venda = new Venda();

            venda.Status = "FINALIZADO";
            venda.TotalItens = Convert.ToInt32(TotalItens);
            venda.ValorTotal = Convert.ToDouble(ValorTotal);
            venda.Recebido = Convert.ToDouble(ValorRecebido);
            venda.Troco = Convert.ToDouble(Troco);

            VendaDAO dao = new VendaDAO();
            if (dao.FinalizarVenda(venda, lastID))
            {
                return Json(new
                {
                    mensagem = "SUCESSO"
                });
            }
            else
            {
                return Json(new
                {
                    mensagem = "ERRO"
                });
            }
        }
        
        public ActionResult ListaVenda()
        {
            VendaDAO dao = new VendaDAO();

            return View(dao.ListarTodos());
        }

        public void ControleDeVendasNaoFinalizada()
        {
            VendaDAO vendaDAO = new VendaDAO();

            List<Venda> listVenda = vendaDAO.GetVendasNaoFinalizadas();

            foreach (var item in listVenda)
            {
                ItemVendaDAO itemVendaDAO = new ItemVendaDAO();

                List<ItemVenda> listItemVenda = itemVendaDAO.ListarPorIDVenda(item);

                foreach (var itemVenda in listItemVenda)
                {
                    LoteDAO loteDAO = new LoteDAO();

                    itemVenda.Venda = item;

                    itemVenda.Lote = loteDAO.ListarSelecionadoID(itemVenda.Lote.ID);

                    itemVenda.Lote.QuantidadeItens = itemVenda.Lote.QuantidadeItens + itemVenda.Quantidade;

                    if (loteDAO.AtualizarQuantidade(itemVenda.Lote.ID, itemVenda.Lote.QuantidadeItens))
                    {
                        itemVendaDAO.DeletarItemVendaNaoFinalizado(itemVenda);
                    }
                }

                vendaDAO.DeletarVendaNaoFinalizada(item);
            }
        }
    }
}

PfcWeb.MVC/Views/Venda/Venda.cshtml
@{
    ViewBag.Title = "Vendas";
}
<nav class="navbar navbar-expand navbar-dark bg-dark static-top">
    <h1 class="navbar-brand mr-1">Prime Stock</h1>
    <a class="ml-auto text-white" href="@Url.Action("MenuFuncCaixa", "Menu")">Inicio</a>
    <a class="ml-auto text-white" href="@Url.Action("Logout", "Usuario")">Sair</a>
</nav>
<div class="container">
    <div class="card card mx-auto mt-5">
        <div class="card-header">Frente de Caixa</div>
        <div class="card-body">
            <table>
                <tr>
                    <td>
                        <div class="form-group">
                            <div class="form-row">
                                <div class="col-md-9">
                                    <div class="form-label-group">
                                        <input autofocus maxlength="13" class="form-control" name="txtBarcode" id="txtBarcode">
                                        <label for="txtBarcode">Codigo de Barras</label>
                                    </div>
                                </div>
                            </div>
                        </div>
                        <br>
                        <div class="form-row">
                            <div class="col-md-12">
                                <div class="form-label-group">
                                    <input type="number" name="txtRecebido" id="txtRecebido">
                                    <label for="txtRecebido">Recebido</label>
                                </div>
                            </div>
                        </div>

                        <br>

                        <div class="form-row">
                            <div class="col-md-4">
                                <h6>Troco: </h6>
                                <h6 id="lblTroco" step=".01">0</h6>
                            </div>

                            <div class="col-md-4">
                                <h6>Total Itens: </h6>
                                <h6 id="lblTotalItens">0</h6>
                            </div>

                            <div class="col-md-4">
                                <h6>Valor Total: </h6>
                                <h6 id="lblTotalAPagar" onchange="setTwoNumberDecimal" type='number' step='0,01'>0</h6>
                            </div>

                            <br>
                        </div>
                        <div class="form-row">
                            <div class="col-md-12">
                                <button align="center" class="btn btn-success" name="btnFinalize" id="btnFinalize" style="width: 100%">Finalizar Compra</button>
                            </div>
                        </div>
                    </td>
                    <td>
                        <div align="right" style="max-width:100%; overflow: scroll; max-height:100%;">
                            <table class="table table-striped table-bordered" align="center" id="tabelaCarrinho">
                                <thead>
                                    <tr>
                                        <th scope="col">ID</th>
                                        <th scope="col">Nome do Item</th>
                                        <th scope="col">Quantidade de Itens</th>
                                        <th scope="col">Valor Unitário (R$)</th>
                                    </tr>
                                </thead>
                                <tbody id="tabelaBody">
                                    @*Tabela à ser populada*@
                                </tbody>
                            </table>
                        </div>
                    </td>
                </tr>
            </table>
        </div>
    </div>
</div>

<div id="myModal" class="modal fade" tabindex="-1" role="dialog">
    <div class="modal-dialog" role="document">
        <div class="modal-content">
            <div class="modal-header">
                <h5 class="modal-title">Quantidade</h5>
                <button type="button" class="close" data-dismiss="modal" aria-label="Close">
                    <span aria-hidden="true">&times;</span>
                </button>
            </div>
            <div class="modal-body">
                <input type="number" value="1" class="form-control" name="txtQuantidade" id="txtQuantidade">
            </div>
            <div class="modal-footer">
                <button type="button" class="btn btn-secondary" data-dismiss="modal">Fechar</button>
                <button type="submit" class="btn btn-success" id="btnAdd" name="btnAdd" data-dismiss="modal">Adicionar</button>
            </div>
        </div>
    </div>
</div>

<div id="modalDelete" class="modal fade" tabindex="-1" role="dialog">
    <div class="modal-dialog" role="document">
        <div class="modal-content">
            <div class="modal-header">
                <h5 class="modal-title">Quantidade</h5>
                <button type="button" class="close" data-dismiss="modal" aria-label="Close">
                    <span aria-hidden="true">&times;</span>
                </button>
            </div>
            <div class="modal-body">
                <input type="number" value="1" class="form-control" name="txtQuantidade" id="txtQuantidade">
            </div>
            <div class="modal-footer">
                <button type="button" class="btn btn-secondary" data-dismiss="modal">Fechar</button>
                <button type="submit" class="btn btn-success" id="btnAdd" name="btnAdd" data-dismiss="modal">Adicionar</button>
            </div>
        </div>
    </div>
</div>

@section scripts{
    <script type="text/javascript">

        function setTwoNumberDecimal(event) {
            this.value = parseFloat(this.value).toFixed(2);
        }

        $(document).ready(function () {
            var totalValor = Number(0);
            var totalItens = Number(0);
            var Barcode;

        $("#txtBarcode").on('keyup', function (e) {
                if (e.key == "Enter") {
                    Barcode = document.getElementById('txtBarcode').value;
                    if (Barcode.lenght != 0) {
                        $('#myModal').modal('show');
                        document.getElementById('txtBarcode').focus();
                        document.getElementById('txtQuantidade').focus();
                    }
                }
            });

      
        $("#btnAdd").click(function () {
            var QuantidadeItens = parseInt(document.getElementById('txtQuantidade').value);
            if (QuantidadeItens > 0) {
                var f = {};
                f.url = '@Url.Action("AdicionarProduto", "Venda")';
                f.type = "POST";
                f.dataType = "json";
                f.data = JSON.stringify({
                    Barcode,
                    QuantidadeItens
                });
                f.contentType = "application/json";
                f.success = function (response) {
                    if (response.produtoID != 0) {
                        document.getElementById('txtBarcode').value = "";
                        
                        var produtoID = "<td>" + response.produtoID + "</td>";
                        var produtoNome = "<td>" + response.produtoNome + "</td>";
                        var produtoQuantidade = "<td>" + QuantidadeItens + "</td>";
                        var produtoValor = "<td type='number' onchange='setTwoNumberDecimal' step='0,01'>" + response.produtoValor + "</td>";

                        totalValor += response.produtoValor * QuantidadeItens;
                        totalItens += QuantidadeItens;
                        document.getElementById("tabelaBody").innerHTML += produtoID + produtoNome + produtoQuantidade + produtoValor;
                        document.getElementById("lblTotalAPagar").innerHTML = totalValor;
                        document.getElementById("lblTotalItens").innerHTML = totalItens;

                        document.getElementById('txtBarcode').focus();
                    } else {
                        if (response.produtoNome == "ERRO QUANTIDADE") {
                            alert("Quantidade Invalida, " + response.produtoQuantidade + " a mais");
                            document.getElementById('txtBarcode').value = "";
                        } else if (response.produtoNome == "ERRO VALIDADE") {
                            alert("Produto não pode ser vendido pois está vencido!");
                            document.getElementById('txtBarcode').value = "";
                        } else if (response.produtoNome == "ERRO PRATELEIRA") {
                            alert("Produto não existe em nenhuma prateleira");
                            document.getElementById('txtBarcode').value = "";
                        }
                        else {
                            alert("Produto Não existente");
                            document.getElementById('txtBarcode').value = "";
                        }
                    }

                };
                f.error = function (response) {
                    alert("Tente Novamente");
                    document.getElementById('txtBarcode').value = "";
                };
                $.ajax(f);
            } else {
                alert("Valor invalido");
            }

            });

        $("#btnFinalize").click(function () {
            if (document.getElementById("lblTotalAPagar").innerText == "0") {
                alert("Nenhum item no carrinho de compras");
            } else {
                var ValorRecebido = parseFloat(document.getElementById('txtRecebido').value);
                var ValorTotal = parseFloat(document.getElementById("lblTotalAPagar").innerText);
                if (document.getElementById('txtRecebido').value <= 0) {
                    alert("Valor Recebido deve ser maior que 0");
                } else if (ValorRecebido < ValorTotal) {
                    alert("Valor menor que Total a Pagar");
                } else {
                    var Troco = ValorRecebido - ValorTotal;
                    document.getElementById("lblTroco").innerText = Troco;
                    var f = {};
                    f.url = '@Url.Action("FinalizarCompra", "Venda")';
                    f.type = "POST";
                    f.dataType = "json";
                    f.data = JSON.stringify({
                        totalItens,
                        ValorTotal,
                        ValorRecebido,
                        Troco
                    });
                    f.contentType = "application/json";
                    f.success = function (response) {
                        if (response.mensagem == "SUCESSO") {
                            alert("Venda efetuada com sucesso - Troco de: R$" + Troco);

                            window.location.reload();
                        } else {
                            alert("Erro ao efetuar a venda, verifique os dados");
                            location.reload();

                        }
                    };
                    f.error = function (response) {
                        alert("Tente Novamente");
                    };
                    $.ajax(f);
                }
            }
        });
    });
    </script>
}