PfcWeb.MVC/Controllers/MenuController.cs
using PfcWeb.Domain.Entities;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using System.Web.Security;

namespace PfcWeb.MVC.Controllers
{
    public class MenuController : Controller
    {
        [Authorize(Roles = "CAIXA")]
        public ActionResult MenuFuncCaixa()
        {
            return View();
        }

        [Authorize(Roles = "ESTOQUE")]
        public ActionResult MenuFuncEstoque()
        {
            return View();
        }

        [Authorize(Roles = "GERENTE")]
        public ActionResult MenuGerente()
        {
            return View();
        }
    }
}

PfcWeb.MVC/Controllers/RelatoriosController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using PFC.Data.DAO;
using PfcWeb.Data.DAO;
using PfcWeb.Domain.Entities;

namespace PfcWeb.MVC.Controllers
{
    [Authorize(Roles = "GERENTE")]
    public class RelatoriosController : Controller
    {
        // GET: Relatorios
        public ActionResult SelecaoRelatorios()
        {
            return View();
        }
        
        public ActionResult VendasPeriodo()
        {
            return View();
        }
        
        [HttpPost]
        public ActionResult VendasPeriodo(string date1, string date2)
        {
            DateTime dateFirst = DateTime.Now;
            DateTime dateSecond = DateTime.Now;

            if (!date1.Equals(""))
            {
                dateFirst = Convert.ToDateTime(date1);
            }
            if (!date2.Equals(""))
            {
                dateSecond = Convert.ToDateTime(date2);
            }

            VendaDAO vendaDAO = new VendaDAO();

            if (!date1.Equals("") && !date2.Equals(""))
            {
                if (dateFirst <= dateSecond)
                {
                    return View(vendaDAO.RelatorioVendasPorPeriodo(dateFirst, dateSecond));
                }
                else
                {
                    TempData["Message"] = string.Format("A primeira data deve ser menor que a segunda");
                    return View();
                }
            }
            else if (!date1.Equals(""))
            {
                return View(vendaDAO.RelatorioVendasAPartirDe(dateFirst));
            }
            else if (!date2.Equals(""))
            {
                return View(vendaDAO.RelatorioVendasAteQue(dateSecond));
            }
            else
            {
                return View(vendaDAO.RelatorioVendasPorPeriodo(DateTime.Now, DateTime.Now));
            }
        }
        
        public ActionResult ProdutosVendidos()
        {
            return View();
        }
        
        [HttpPost]
        public ActionResult ProdutosVendidos(string date1, string date2)
        {
            DateTime dateFirst = DateTime.Now;
            DateTime dateSecond = DateTime.Now;

            if (!date1.Equals(""))
            {
                dateFirst = Convert.ToDateTime(date1);
            }
            if (!date2.Equals(""))
            {
                dateSecond = Convert.ToDateTime(date2);
            }

            VendaDAO vendaDAO = new VendaDAO();

            if (!date1.Equals("") && !date2.Equals(""))
            {
                if (dateFirst <= dateSecond)
                {
                    List<Venda> listVenda = vendaDAO.RelatorioVendasPorPeriodo(dateFirst, dateSecond);

                    List<ItemVenda> listItemVenda = new List<ItemVenda>();
                    ItemVendaDAO itemVendaDAO = new ItemVendaDAO();

                    foreach (var item in listVenda)
                    {
                        List<ItemVenda> listItemVendaAux = itemVendaDAO.ListarPorIDVenda(item);

                        foreach (var itemAux in listItemVendaAux)
                        {
                            itemAux.Venda = item;
                            listItemVenda.Add(itemAux);

                        }
                    }

                    LoteDAO loteDAO = new LoteDAO();
                    ProdutoDAO produtoDAO = new ProdutoDAO();

                    foreach (var item in listItemVenda)
                    {
                        item.Lote = loteDAO.ListarSelecionadoID(item.Lote.ID);

                        item.Lote.Produto = produtoDAO.ListarSelecionadoID(item.Lote.Produto.ID);
                    }

                    return View(listItemVenda);
                }
                else
                {
                    TempData["Message"] = string.Format("A primeira data deve ser menor que a segunda");
                    return View();
                }
            }
            else if (!date1.Equals(""))
            {
                List<Venda> listVenda = vendaDAO.RelatorioVendasAPartirDe(dateFirst);

                List<ItemVenda> listItemVenda = new List<ItemVenda>();
                ItemVendaDAO itemVendaDAO = new ItemVendaDAO();

                foreach (var item in listVenda)
                {
                    List<ItemVenda> listItemVendaAux = itemVendaDAO.ListarPorIDVenda(item);

                    listItemVendaAux[0].Venda = item;
                    listItemVenda.Add(listItemVendaAux[0]);

                    foreach (var itemAux in listItemVendaAux)
                    {
                        itemAux.Venda = item;
                        listItemVenda.Add(itemAux);

                    }

                }

                LoteDAO loteDAO = new LoteDAO();

                ProdutoDAO produtoDAO = new ProdutoDAO();

                foreach (var item in listItemVenda)
                {
                    item.Lote = loteDAO.ListarSelecionadoID(item.Lote.ID);

                    item.Lote.Produto = produtoDAO.ListarSelecionadoID(item.Lote.Produto.ID);
                }

                return View(listItemVenda);
            }
            else if (!date2.Equals(""))
            {
                List<Venda> listVenda = vendaDAO.RelatorioVendasAteQue(dateSecond);

                List<ItemVenda> listItemVenda = new List<ItemVenda>();
                ItemVendaDAO itemVendaDAO = new ItemVendaDAO();

                foreach (var item in listVenda)
                {
                    List<ItemVenda> listItemVendaAux = itemVendaDAO.ListarPorIDVenda(item);

                    foreach (var itemAux in listItemVendaAux)
                    {
                        itemAux.Venda = item;
                        listItemVenda.Add(itemAux);

                    }
                }

                LoteDAO loteDAO = new LoteDAO();

                ProdutoDAO produtoDAO = new ProdutoDAO();

                foreach (var item in listItemVenda)
                {
                    item.Lote = loteDAO.ListarSelecionadoID(item.Lote.ID);

                    item.Lote.Produto = produtoDAO.ListarSelecionadoID(item.Lote.Produto.ID);
                }

                return View(listItemVenda);
            }
            else
            {
                List<Venda> listVenda = vendaDAO.RelatorioVendasPorPeriodo(DateTime.Now, DateTime.Now);

                List<ItemVenda> listItemVenda = new List<ItemVenda>();
                ItemVendaDAO itemVendaDAO = new ItemVendaDAO();

                foreach (var item in listVenda)
                {
                    List<ItemVenda> listItemVendaAux = itemVendaDAO.ListarPorIDVenda(item);

                    foreach (var itemAux in listItemVendaAux)
                    {
                        itemAux.Venda = item;
                        listItemVenda.Add(itemAux);

                    }
                }

                LoteDAO loteDAO = new LoteDAO();

                ProdutoDAO produtoDAO = new ProdutoDAO();

                foreach (var item in listItemVenda)
                {
                    item.Lote = loteDAO.ListarSelecionadoID(item.Lote.ID);

                    item.Lote.Produto = produtoDAO.ListarSelecionadoID(item.Lote.Produto.ID);
                }

                return View(listItemVenda);
            }
        }
        
        public ActionResult SelecionarCategoriaLotes()
        {
            Lote lote = new Lote();

            CategoriaDAO categoriaDAO = new CategoriaDAO();

            ViewBag.Categoria = categoriaDAO.ListarTodos();

            return View(lote);
        }
        
        [HttpPost]
        public ActionResult LotesDescartados(Categoria categoria)
        {
            LoteDAO loteDAO = new LoteDAO();

            List<Lote> listVendas = loteDAO.ListarDesativadosPorCategoria(categoria);

            ProdutoDAO produtoDAO = new ProdutoDAO();
            CategoriaDAO categoriaDAO = new CategoriaDAO();

            foreach (var item in listVendas)
            {
                item.Produto = produtoDAO.ListarSelecionadoID(item.Produto.ID);
                item.Categoria = categoriaDAO.ListarSelecionadoID(item.Categoria.ID);
            }

            return View(listVendas);
        }
    }
}

PfcWeb.MVC/Views/Relatorios/LotesDescartados.cshtml
@model IEnumerable<PfcWeb.Domain.Entities.Lote>
@{
    ViewBag.Title = "Lotes descartados";
}
<nav class="navbar navbar-expand navbar-dark bg-dark static-top">
    <h1 class="navbar-brand mr-1">Prime Stock</h1>
    <a class="ml-auto text-white" href="@Url.Action("SelecaoRelatorios", "Relatorios")">Seleção de relatórios</a>
    <a class="ml-auto text-white" href="@Url.Action("Logout", "Usuario")">Sair</a>
</nav>
@if (Model != null)
{
    <div class="container">
        <div class="card text-white mx-auto mt-5 bg-dark">
            <div class="card-header">Relatorio de lotes descartados</div>
            <div class="card-body">
                <table class="table table-hover">
                    <thead>
                        <tr>
                            <th scope="col">
                                ID
                            </th>
                            <th scope="col">
                                Quantidade
                            </th>
                            <th scope="col">
                                Data de Entrada
                            </th>
                            <th scope="col">
                                Data de Validade
                            </th>
                            <th scope="col">
                                Categoria
                            </th>
                            <th scope="col">
                                Produto
                            </th>
                        </tr>
                    </thead>
                    <tbody>
                        @*Conteúdo da tabela*@
                        @foreach (var item in Model)
                        {
                        <tr>
                            <td>
                                @Html.DisplayFor(itemModel => item.ID)
                            </td>
                            <td>
                                @Html.DisplayFor(itemModel => item.QuantidadeItens)
                            </td>
                            <td>
                                @Html.DisplayFor(itemModel => item.DataEntrada)
                            </td>
                            <td>
                                @Html.DisplayFor(itemModel => item.DataValidade)
                            </td>
                            <td>
                                @Html.DisplayFor(itemModel => item.Categoria.Descricao)
                            </td>
                            <td>
                                @Html.DisplayFor(itemModel => item.Produto.Nome)
                            </td>
                        </tr>
                        }
                    </tbody>
                </table>
            </div>
        </div>
    </div>
}

PfcWeb.MVC/Views/Relatorios/ProdutosVendidos.cshtml
@model IEnumerable<PfcWeb.Domain.Entities.ItemVenda>
@{
    ViewBag.Title = "Vendas por período";
}
@section Scripts {
    <script type="text/javascript">
        window.onload = function () {
            $('#myModal').modal('show');
        };</script>
}
@if (@TempData["Message"] != null)
{
    <div id="myModal" class="modal fade" tabindex="-1" role="dialog">
        <div class="modal-dialog" role="document">
            <div class="modal-content">
                <div class="modal-header">
                    <h5 class="modal-title">Aviso</h5>
                    <button type="button" class="close" data-dismiss="modal" aria-label="Close">
                        <span aria-hidden="true">&times;</span>
                    </button>
                </div>
                <div class="modal-body">
                    <p>@TempData["Message"].ToString()</p>
                </div>
                <div class="modal-footer">
                    <button type="button" class="btn btn-secondary" data-dismiss="modal">Fechar</button>
                </div>
            </div>
        </div>
    </div>
}
<nav class="navbar navbar-expand navbar-dark bg-dark static-top">
    <h1 class="navbar-brand mr-1">Prime Stock</h1>
    <a class="ml-auto text-white" href="@Url.Action("SelecaoRelatorios", "Relatorios")">Seleção de relatórios</a>
    <a class="ml-auto text-white" href="@Url.Action("Logout", "Usuario")">Sair</a>
</nav>
<div class="container">
    <div class="card card-register text-white mx-auto mt-5 bg-dark">
        <div class="card-header">Busca por periodo</div>
        <div class="card-body">
            <form method="post" action="@Url.Action("ProdutosVendidos", "Relatorios")">
                <div class="form-group">
                    <div class="form-row">
                        <div class="col-md-6">
                            <label>A partir de:</label>
                            <input type="date" name="date1" id="date1" class="form-control">
                        </div>
                        <div class="col-md-6">
                            <label>Até:</label>
                            <input type="date" name="date2" id="date2" class="form-control">
                        </div>
                    </div>
                </div>
                <button type="submit" class="btn btn-success btn-block">Buscar</button>
            </form>
        </div>
    </div>
</div>
<br>
@if (Model != null)
{
    <div class="container">
        <div class="card text-white mx-auto mt-5 bg-dark">
            <div class="card-header">Relatorio de produtos vendidos</div>
            <div class="card-body">
                <table class="table table-hover">
                    <thead>
                        <tr>
                            <th scope="col">
                                ID Venda
                            </th>
                            <th scope="col">
                                Produto
                            </th>
                            <th scope="col">
                                Total Itens
                            </th>
                            <th scope="col">
                                Data de Venda
                            </th>
                        </tr>
                    </thead>
                    <tbody>
                        @*Conteúdo da tabela*@
                        @foreach (var item in Model)
                        {
                            <tr>
                                <td>
                                    @Html.DisplayFor(itemModel => item.Venda.ID)
                                </td>
                                <td>
                                    @Html.DisplayFor(itemModel => item.Lote.Produto.Nome)
                                </td>
                                <td>
                                    @Html.DisplayFor(itemModel => item.Venda.TotalItens)
                                </td>
                                <td>
                                    @Html.DisplayFor(itemModel => item.Venda.DataHora)
                                </td>
                            </tr>
                        }
                    </tbody>
                </table>
            </div>
        </div>
    </div>
}

PfcWeb.MVC/Views/Relatorios/SelecaoRelatorios.cshtml
@{
    ViewBag.Title = "Relatorios";
}
@section Scripts {
    <script type="text/javascript">
        window.onload = function () {
            $('#myModal').modal('show');
        };</script>
}
@if (@TempData["Message"] != null)
{
    <div id="myModal" class="modal fade" tabindex="-1" role="dialog">
        <div class="modal-dialog" role="document">
            <div class="modal-content">
                <div class="modal-header">
                    <h5 class="modal-title">Aviso</h5>
                    <button type="button" class="close" data-dismiss="modal" aria-label="Close">
                        <span aria-hidden="true">&times;</span>
                    </button>
                </div>
                <div class="modal-body">
                    <p>@TempData["Message"].ToString()</p>
                </div>
                <div class="modal-footer">
                    <button type="button" class="btn btn-secondary" data-dismiss="modal">Fechar</button>
                </div>
            </div>
        </div>
    </div>
}
<nav class="navbar navbar-expand navbar-dark bg-dark static-top">
    <h1 class="navbar-brand mr-1">Prime Stock</h1>
    <a class="ml-auto text-white" href="@Url.Action("MenuGerente", "Menu")">Início</a>
    <a class="ml-auto text-white" href="@Url.Action("Logout", "Usuario")">Sair</a>
</nav>
<div class="container">
    <br>
    <br>
    <div class="row justify-content-md-center col-xl-12">
        <div class="col-xl-6 col-sm-6 mb-3">
            <div class="card text-white bg-danger o-hidden h-100">
                <div class="card-body">
                    <div class="card-body-icon">
                        <i class="fas fa-fw fa-calendar-check-o"></i>
                    </div>
                    <h2>Vendas por período</h2>
                    <div class="mr-3">Consulte o volume de vendas dos produtos em determinado período</div>
                </div>
                <a class="card-footer text-white clearfix small z-1" href="@Url.Action("VendasPeriodo", "Relatorios")">
                    <i class="float-right medium material-icons">done</i>
                </a>
            </div>
        </div>
        <div class="col-xl-6 col-sm-6 mb-3">
            <div class="card text-white bg-warning o-hidden h-100">
                <div class="card-body">
                    <div class="card-body-icon">
                        <i class="fas fa-fw fa-bar-chart"></i>
                    </div>
                    <h2>Produtos vendido</h2>
                    <div class="mr-3">Consulte quais são os produtos vendido em determinado período</div>
                </div>
                <a class="card-footer text-white clearfix small z-1" href="@Url.Action("ProdutosVendidos", "Relatorios")">
                    <i class="float-right medium material-icons">done</i>
                </a>
            </div>
        </div><br />
        <div class="col-xl-6 col-sm-6 mb-3">
            <div class="card text-white bg-info o-hidden h-100">
                <div class="card-body">
                    <div class="card-body-icon">
                        <i class="fas fa-fw fa-map"></i>
                    </div>
                    <h2>Lotes descartados</h2>
                    <div class="mr-3">Consulte todos os lotes por categoria que foram descartados </div>
                </div>
                <a class="card-footer text-white clearfix small z-1" href="@Url.Action("SelecionarCategoriaLotes", "Relatorios")">
                    <i class="float-right medium material-icons">done</i>
                </a>
            </div>
        </div>
    </div>
</div>

PfcWeb.MVC/Views/Relatorios/SelecionarCategoriaLotes.cshtml
@model PfcWeb.Domain.Entities.Lote
@{
    ViewBag.Title = "SelecionarCategoriaLotes";
}

@section Scripts {
    <script type="text/javascript">
        window.onload = function () {
            $('#myModal').modal('show');
        };</script>
}

@if (@TempData["Message"] != null)
{
    <div id="myModal" class="modal fade" tabindex="-1" role="dialog">
        <div class="modal-dialog" role="document">
            <div class="modal-content">
                <div class="modal-header">
                    <h5 class="modal-title">Aviso</h5>
                    <button type="button" class="close" data-dismiss="modal" aria-label="Close">
                        <span aria-hidden="true">&times;</span>
                    </button>
                </div>
                <div class="modal-body">
                    <p>@TempData["Message"].ToString()</p>
                </div>
                <div class="modal-footer">
                    <button type="button" class="btn btn-secondary" data-dismiss="modal">Fechar</button>
                </div>
            </div>
        </div>
    </div>
}

<nav class="navbar navbar-expand navbar-dark bg-dark static-top">
    <h1 class="navbar-brand mr-1">Prime Stock</h1>
    <a class="ml-auto text-white" href="@Url.Action("SelecaoRelatorios", "Relatorios")">Seleção de relatórios</a>
    <a class="ml-auto text-white" href="@Url.Action("Logout", "Usuario")">Sair</a>
</nav>
<div class="container">
    <div class="card card-register text-white mx-auto mt-5 bg-dark">
        <div class="card-header">Busca por periodo</div>
        <div class="card-body">
            <form method="post" action="@Url.Action("LotesDesativados", "Relatorios")">
                <div class="form-group">
                    <div class="col-md-6">
                        <label>Categoria</label>
                        <div class="form-label-group">
                            @Html.DropDownListFor(model => model.Categoria.ID, new SelectList(ViewBag.Categoria, "ID", "Descricao"),
                                                    new { @class = "form-control", required = "required" })
                            @Html.ValidationMessageFor(model => model.Categoria.ID, "", new { @class = "text-danger" })
                        </div>
                    </div>
                </div>
                <button type="submit" class="btn btn-success btn-block">Buscar</button>
            </form>
        </div>
    </div>
</div>

PfcWeb.MVC/Views/Relatorios/VendasPeriodo.cshtml
@model IEnumerable<PfcWeb.Domain.Entities.Venda>
@{
    ViewBag.Title = "Vendas por período";
}

@section Scripts {
    <script type="text/javascript">
        window.onload = function () {
            $('#myModal').modal('show');
        };</script>
}
@if (@TempData["Message"] != null)
{
    <div id="myModal" class="modal fade" tabindex="-1" role="dialog">
        <div class="modal-dialog" role="document">
            <div class="modal-content">
                <div class="modal-header">
                    <h5 class="modal-title">Aviso</h5>
                    <button type="button" class="close" data-dismiss="modal" aria-label="Close">
                        <span aria-hidden="true">&times;</span>
                    </button>
                </div>
                <div class="modal-body">
                    <p>@TempData["Message"].ToString()</p>
                </div>
                <div class="modal-footer">
                    <button type="button" class="btn btn-secondary" data-dismiss="modal">Fechar</button>
                </div>
            </div>
        </div>
    </div>
}

<nav class="navbar navbar-expand navbar-dark bg-dark static-top">
    <h1 class="navbar-brand mr-1">Prime Stock</h1>
    <a class="ml-auto text-white" href="@Url.Action("SelecaoRelatorios", "Relatorios")">Seleção de relatórios</a>
    <a class="ml-auto text-white" href="@Url.Action("Logout", "Usuario")">Sair</a>
</nav>
<div class="container">
    <div class="card card-register text-white mx-auto mt-5 bg-dark">
        <div class="card-header">Busca por periodo</div>
        <div class="card-body">
            <form method="post" action="@Url.Action("VendasPeriodo", "Relatorios")">
                <div class="form-group">
                    <div class="form-row">
                        <div class="col-md-6">
                            <label>A partir de:</label>
                            <input type="date" name="date1" id="date1" class="form-control">
                        </div>
                        <div class="col-md-6">
                            <label>Até:</label>
                            <input type="date" name="date2" id="date2" class="form-control">
                        </div>
                    </div>
                </div>
                <button type="submit" class="btn btn-success btn-block">Buscar</button>
            </form>
        </div>
    </div>
</div>
<br>
@if (Model != null)
{
    <div class="container">
        <div class="card text-white mx-auto mt-5 bg-dark">
            <div class="card-header">Relatorio de vendas por periodo</div>
            <div class="card-body">
                <table class="table table-hover">
                    <thead>
                        <tr>
                            <th scope="col">ID </th>

                            <th scope="col">Data compra</th>

                            <th scope="col"> Valor total (R$)</th>
                        </tr>
                    </thead>
                    <tbody>
                        @*Conteúdo da tabela*@
                        @foreach (var venda in Model)
                        {
                        <tr>
                            <td>
                                @Html.DisplayFor(modelVenda => venda.ID)
                            </td>
                            <td>
                                @Html.DisplayFor(modelVenda => venda.DataHora)
                            </td>
                            <td>
                                @Html.DisplayFor(modelVenda => venda.ValorTotal)
                            </td>
                        </tr>
                        }
                    </tbody>
                </table>
            </div>
        </div>
    </div>
}